// Package storage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package storage

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BackupTaskResult.
const (
	BackupTaskResultFailed  BackupTaskResult = "failed"
	BackupTaskResultSkipped BackupTaskResult = "skipped"
	BackupTaskResultSuccess BackupTaskResult = "success"
	BackupTaskResultUnknown BackupTaskResult = "unknown"
	BackupTaskResultWarning BackupTaskResult = "warning"
)

// Valid indicates whether the value is a known member of the BackupTaskResult enum.
func (e BackupTaskResult) Valid() bool {
	switch e {
	case BackupTaskResultFailed:
		return true
	case BackupTaskResultSkipped:
		return true
	case BackupTaskResultSuccess:
		return true
	case BackupTaskResultUnknown:
		return true
	case BackupTaskResultWarning:
		return true
	default:
		return false
	}
}

// Defines values for BackupTaskStatus.
const (
	Error     BackupTaskStatus = "error"
	Idle      BackupTaskStatus = "idle"
	Running   BackupTaskStatus = "running"
	Suspended BackupTaskStatus = "suspended"
)

// Valid indicates whether the value is a known member of the BackupTaskStatus enum.
func (e BackupTaskStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Idle:
		return true
	case Running:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for DiskStatus.
const (
	DiskStatusCritical DiskStatus = "critical"
	DiskStatusFailing  DiskStatus = "failing"
	DiskStatusNormal   DiskStatus = "normal"
	DiskStatusWarning  DiskStatus = "warning"
)

// Valid indicates whether the value is a known member of the DiskStatus enum.
func (e DiskStatus) Valid() bool {
	switch e {
	case DiskStatusCritical:
		return true
	case DiskStatusFailing:
		return true
	case DiskStatusNormal:
		return true
	case DiskStatusWarning:
		return true
	default:
		return false
	}
}

// Defines values for VolumeStatus.
const (
	Crashed   VolumeStatus = "crashed"
	Degraded  VolumeStatus = "degraded"
	Normal    VolumeStatus = "normal"
	Repairing VolumeStatus = "repairing"
)

// Valid indicates whether the value is a known member of the VolumeStatus enum.
func (e VolumeStatus) Valid() bool {
	switch e {
	case Crashed:
		return true
	case Degraded:
		return true
	case Normal:
		return true
	case Repairing:
		return true
	default:
		return false
	}
}

// BackupTask A backup task from a NAS backup service (e.g. Hyper Backup,
// Glacier Backup). Represents a configured backup job and the
// outcome of its most recent run.
type BackupTask struct {
	// Device Identifier of the backend device that owns this task.
	Device string `json:"device"`

	// Id Globally unique backup task identifier in the form
	// `{device}.{taskId}`. Use this value directly in path parameters.
	Id string `json:"id"`

	// LastResult Outcome of the most recent backup run.
	LastResult BackupTaskResult `json:"lastResult"`

	// Name Human-readable task name as configured in the backup service.
	Name string `json:"name"`

	// Status Current state of a backup task.
	Status BackupTaskStatus `json:"status"`

	// Type Backup service type. Values depend on the backend (e.g.
	// `hyperBackup`, `glacierBackup`).
	Type string `json:"type"`
}

// BackupTaskDetail defines model for BackupTaskDetail.
type BackupTaskDetail struct {
	// Device Identifier of the backend device that owns this task.
	Device string `json:"device"`

	// Folders List of source folder paths included in this backup task.
	Folders *[]string `json:"folders,omitempty"`

	// Id Globally unique backup task identifier in the form
	// `{device}.{taskId}`. Use this value directly in path parameters.
	Id string `json:"id"`

	// LastResult Outcome of the most recent backup run.
	LastResult BackupTaskResult `json:"lastResult"`

	// LastRunAt Timestamp of the most recent backup run completion.
	LastRunAt *time.Time `json:"lastRunAt,omitempty"`

	// Name Human-readable task name as configured in the backup service.
	Name string `json:"name"`

	// NextRunAt Scheduled time of the next backup run.
	NextRunAt *time.Time `json:"nextRunAt,omitempty"`

	// Size Total size of the most recent backup.
	Size *Bytes `json:"size,omitempty"`

	// Status Current state of a backup task.
	Status BackupTaskStatus `json:"status"`

	// Type Backup service type. Values depend on the backend (e.g.
	// `hyperBackup`, `glacierBackup`).
	Type string `json:"type"`
}

// BackupTaskList List of backup tasks.
type BackupTaskList struct {
	// Items Backup tasks matching the query. Empty array, never null.
	Items []BackupTask `json:"items"`
}

// BackupTaskResult Outcome of the most recent backup run.
type BackupTaskResult string

// BackupTaskStatus Current state of a backup task.
type BackupTaskStatus string

// Bytes A quantity expressed in bytes.
type Bytes = int64

// DiskStatus Health status of a physical disk based on SMART diagnostics and
// backend health checks.
type DiskStatus string

// Problem RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code echoed for convenience.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem.
	Title string `json:"title"`

	// Type URI reference identifying the problem type.
	Type string `json:"type"`
}

// Volume A storage volume reported by a NAS or storage backend.
type Volume struct {
	// Device Identifier of the backend device that owns this volume.
	Device string `json:"device"`

	// FileSystem Filesystem type of the volume.
	FileSystem string `json:"fileSystem"`

	// Id Globally unique volume identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// Name Original volume name as reported by the backend.
	Name string `json:"name"`

	// RaidType RAID level or storage pool type (e.g. SHR, RAID 1, RAID 5, basic).
	RaidType string `json:"raidType"`

	// Status Health status of a storage volume. Maps to backend-reported states
	// (e.g. Synology DSM volume status).
	Status VolumeStatus `json:"status"`

	// TotalBytes Total capacity of the volume in bytes.
	TotalBytes Bytes `json:"totalBytes"`

	// UsedBytes Used space on the volume in bytes.
	UsedBytes Bytes `json:"usedBytes"`
}

// VolumeDetail defines model for VolumeDetail.
type VolumeDetail struct {
	// Device Identifier of the backend device that owns this volume.
	Device string `json:"device"`

	// Disks Physical disks backing this volume. Empty array, never null.
	Disks []VolumeDisk `json:"disks"`

	// FileSystem Filesystem type of the volume.
	FileSystem string `json:"fileSystem"`

	// Id Globally unique volume identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// MountPath Filesystem mount point of the volume on the backend host.
	MountPath string `json:"mountPath"`

	// Name Original volume name as reported by the backend.
	Name string `json:"name"`

	// PoolStatus Health status of the underlying storage pool. May differ from the volume status during a rebuild or repair.
	PoolStatus VolumeStatus `json:"poolStatus"`

	// RaidType RAID level or storage pool type (e.g. SHR, RAID 1, RAID 5, basic).
	RaidType string `json:"raidType"`

	// Status Health status of a storage volume. Maps to backend-reported states
	// (e.g. Synology DSM volume status).
	Status VolumeStatus `json:"status"`

	// TotalBytes Total capacity of the volume in bytes.
	TotalBytes Bytes `json:"totalBytes"`

	// UsedBytes Used space on the volume in bytes.
	UsedBytes Bytes `json:"usedBytes"`
}

// VolumeDisk Physical disk that backs a storage volume.
type VolumeDisk struct {
	// Id Disk slot identifier as reported by the backend.
	Id string `json:"id"`

	// Model Hardware model name of the disk.
	Model string `json:"model"`

	// Status Health status of a physical disk based on SMART diagnostics and
	// backend health checks.
	Status DiskStatus `json:"status"`

	// TemperatureCelsius Current disk temperature in degrees Celsius.
	TemperatureCelsius int `json:"temperatureCelsius"`

	// TotalBytes Total physical capacity of the disk in bytes.
	TotalBytes Bytes `json:"totalBytes"`
}

// VolumeList List of storage volumes.
type VolumeList struct {
	// Items Storage volumes matching the query. Empty array, never null.
	Items []Volume `json:"items"`
}

// VolumeStatus Health status of a storage volume. Maps to backend-reported states
// (e.g. Synology DSM volume status).
type VolumeStatus string

// DeviceFilter defines model for DeviceFilter.
type DeviceFilter = string

// BadRequest RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type BadRequest = Problem

// Forbidden RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Forbidden = Problem

// InternalServerError RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type InternalServerError = Problem

// NotFound RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type NotFound = Problem

// TooManyRequests RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListBackupsParams defines parameters for ListBackups.
type ListBackupsParams struct {
	// Device Filter results to a specific backend device by its identifier.
	// Omit to return results from all devices.
	Device *DeviceFilter `form:"device,omitempty" json:"device,omitempty"`
}

// ListStorageVolumesParams defines parameters for ListStorageVolumes.
type ListStorageVolumesParams struct {
	// Device Filter results to a specific backend device by its identifier.
	// Omit to return results from all devices.
	Device *DeviceFilter `form:"device,omitempty" json:"device,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List backups
	// (GET /storage/backups)
	ListBackups(w http.ResponseWriter, r *http.Request, params ListBackupsParams)
	// Get a backup
	// (GET /storage/backups/{backupId})
	GetBackup(w http.ResponseWriter, r *http.Request, backupId string)
	// List storage volumes
	// (GET /storage/volumes)
	ListStorageVolumes(w http.ResponseWriter, r *http.Request, params ListStorageVolumesParams)
	// Get a storage volume
	// (GET /storage/volumes/{volumeId})
	GetStorageVolume(w http.ResponseWriter, r *http.Request, volumeId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List backups
// (GET /storage/backups)
func (_ Unimplemented) ListBackups(w http.ResponseWriter, r *http.Request, params ListBackupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a backup
// (GET /storage/backups/{backupId})
func (_ Unimplemented) GetBackup(w http.ResponseWriter, r *http.Request, backupId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List storage volumes
// (GET /storage/volumes)
func (_ Unimplemented) ListStorageVolumes(w http.ResponseWriter, r *http.Request, params ListStorageVolumesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a storage volume
// (GET /storage/volumes/{volumeId})
func (_ Unimplemented) GetStorageVolume(w http.ResponseWriter, r *http.Request, volumeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBackups operation middleware
func (siw *ServerInterfaceWrapper) ListBackups(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read:storage"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBackupsParams

	// ------------- Optional query parameter "device" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "device", r.URL.Query(), &params.Device, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "device"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBackups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBackup operation middleware
func (siw *ServerInterfaceWrapper) GetBackup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "backupId" -------------
	var backupId string

	err = runtime.BindStyledParameterWithOptions("simple", "backupId", chi.URLParam(r, "backupId"), &backupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read:storage"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBackup(w, r, backupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStorageVolumes operation middleware
func (siw *ServerInterfaceWrapper) ListStorageVolumes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read:storage"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStorageVolumesParams

	// ------------- Optional query parameter "device" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "device", r.URL.Query(), &params.Device, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "device"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStorageVolumes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStorageVolume operation middleware
func (siw *ServerInterfaceWrapper) GetStorageVolume(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "volumeId" -------------
	var volumeId string

	err = runtime.BindStyledParameterWithOptions("simple", "volumeId", chi.URLParam(r, "volumeId"), &volumeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "volumeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read:storage"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStorageVolume(w, r, volumeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/storage/backups", wrapper.ListBackups)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/storage/backups/{backupId}", wrapper.GetBackup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/storage/volumes", wrapper.ListStorageVolumes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/storage/volumes/{volumeId}", wrapper.GetStorageVolume)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ListBackupsRequestObject struct {
	Params ListBackupsParams
}

type ListBackupsResponseObject interface {
	VisitListBackupsResponse(w http.ResponseWriter) error
}

type ListBackups200JSONResponse BackupTaskList

func (response ListBackups200JSONResponse) VisitListBackupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBackups401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListBackups401ApplicationProblemPlusJSONResponse) VisitListBackupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBackups403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListBackups403ApplicationProblemPlusJSONResponse) VisitListBackupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListBackups429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListBackups429ApplicationProblemPlusJSONResponse) VisitListBackupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListBackups500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ListBackups500ApplicationProblemPlusJSONResponse) VisitListBackupsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackupRequestObject struct {
	BackupId string `json:"backupId"`
}

type GetBackupResponseObject interface {
	VisitGetBackupResponse(w http.ResponseWriter) error
}

type GetBackup200JSONResponse BackupTaskDetail

func (response GetBackup200JSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackup400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetBackup400ApplicationProblemPlusJSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackup401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetBackup401ApplicationProblemPlusJSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackup403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetBackup403ApplicationProblemPlusJSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackup404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetBackup404ApplicationProblemPlusJSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackup429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetBackup429ApplicationProblemPlusJSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetBackup500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetBackup500ApplicationProblemPlusJSONResponse) VisitGetBackupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageVolumesRequestObject struct {
	Params ListStorageVolumesParams
}

type ListStorageVolumesResponseObject interface {
	VisitListStorageVolumesResponse(w http.ResponseWriter) error
}

type ListStorageVolumes200JSONResponse VolumeList

func (response ListStorageVolumes200JSONResponse) VisitListStorageVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageVolumes401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListStorageVolumes401ApplicationProblemPlusJSONResponse) VisitListStorageVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageVolumes403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListStorageVolumes403ApplicationProblemPlusJSONResponse) VisitListStorageVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageVolumes429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListStorageVolumes429ApplicationProblemPlusJSONResponse) VisitListStorageVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageVolumes500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ListStorageVolumes500ApplicationProblemPlusJSONResponse) VisitListStorageVolumesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolumeRequestObject struct {
	VolumeId string `json:"volumeId"`
}

type GetStorageVolumeResponseObject interface {
	VisitGetStorageVolumeResponse(w http.ResponseWriter) error
}

type GetStorageVolume200JSONResponse VolumeDetail

func (response GetStorageVolume200JSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolume400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetStorageVolume400ApplicationProblemPlusJSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolume401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetStorageVolume401ApplicationProblemPlusJSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolume403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetStorageVolume403ApplicationProblemPlusJSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolume404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetStorageVolume404ApplicationProblemPlusJSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolume429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetStorageVolume429ApplicationProblemPlusJSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetStorageVolume500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetStorageVolume500ApplicationProblemPlusJSONResponse) VisitGetStorageVolumeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List backups
	// (GET /storage/backups)
	ListBackups(ctx context.Context, request ListBackupsRequestObject) (ListBackupsResponseObject, error)
	// Get a backup
	// (GET /storage/backups/{backupId})
	GetBackup(ctx context.Context, request GetBackupRequestObject) (GetBackupResponseObject, error)
	// List storage volumes
	// (GET /storage/volumes)
	ListStorageVolumes(ctx context.Context, request ListStorageVolumesRequestObject) (ListStorageVolumesResponseObject, error)
	// Get a storage volume
	// (GET /storage/volumes/{volumeId})
	GetStorageVolume(ctx context.Context, request GetStorageVolumeRequestObject) (GetStorageVolumeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBackups operation middleware
func (sh *strictHandler) ListBackups(w http.ResponseWriter, r *http.Request, params ListBackupsParams) {
	var request ListBackupsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBackups(ctx, request.(ListBackupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBackups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBackupsResponseObject); ok {
		if err := validResponse.VisitListBackupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBackup operation middleware
func (sh *strictHandler) GetBackup(w http.ResponseWriter, r *http.Request, backupId string) {
	var request GetBackupRequestObject

	request.BackupId = backupId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBackup(ctx, request.(GetBackupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBackup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBackupResponseObject); ok {
		if err := validResponse.VisitGetBackupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStorageVolumes operation middleware
func (sh *strictHandler) ListStorageVolumes(w http.ResponseWriter, r *http.Request, params ListStorageVolumesParams) {
	var request ListStorageVolumesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStorageVolumes(ctx, request.(ListStorageVolumesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStorageVolumes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStorageVolumesResponseObject); ok {
		if err := validResponse.VisitListStorageVolumesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStorageVolume operation middleware
func (sh *strictHandler) GetStorageVolume(w http.ResponseWriter, r *http.Request, volumeId string) {
	var request GetStorageVolumeRequestObject

	request.VolumeId = volumeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStorageVolume(ctx, request.(GetStorageVolumeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStorageVolume")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStorageVolumeResponseObject); ok {
		if err := validResponse.VisitGetStorageVolumeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
