// Package docker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package docker

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ContainerDetailRestartPolicy.
const (
	Always        ContainerDetailRestartPolicy = "always"
	No            ContainerDetailRestartPolicy = "no"
	OnFailure     ContainerDetailRestartPolicy = "on-failure"
	UnlessStopped ContainerDetailRestartPolicy = "unless-stopped"
)

// Valid indicates whether the value is a known member of the ContainerDetailRestartPolicy enum.
func (e ContainerDetailRestartPolicy) Valid() bool {
	switch e {
	case Always:
		return true
	case No:
		return true
	case OnFailure:
		return true
	case UnlessStopped:
		return true
	default:
		return false
	}
}

// Defines values for ContainerStatus.
const (
	Dead       ContainerStatus = "dead"
	Paused     ContainerStatus = "paused"
	Restarting ContainerStatus = "restarting"
	Running    ContainerStatus = "running"
	Stopped    ContainerStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ContainerStatus enum.
func (e ContainerStatus) Valid() bool {
	switch e {
	case Dead:
		return true
	case Paused:
		return true
	case Restarting:
		return true
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for PortBindingProtocol.
const (
	Tcp PortBindingProtocol = "tcp"
	Udp PortBindingProtocol = "udp"
)

// Valid indicates whether the value is a known member of the PortBindingProtocol enum.
func (e PortBindingProtocol) Valid() bool {
	switch e {
	case Tcp:
		return true
	case Udp:
		return true
	default:
		return false
	}
}

// Defines values for VolumeMountMode.
const (
	Ro VolumeMountMode = "ro"
	Rw VolumeMountMode = "rw"
)

// Valid indicates whether the value is a known member of the VolumeMountMode enum.
func (e VolumeMountMode) Valid() bool {
	switch e {
	case Ro:
		return true
	case Rw:
		return true
	default:
		return false
	}
}

// Bytes A quantity expressed in bytes.
type Bytes = int64

// Container A container running on a Docker-compatible backend.
type Container struct {
	// Device Identifier of the backend device running this container.
	Device string `json:"device"`

	// Id Globally unique container identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// Image Container image reference including tag or digest.
	Image string `json:"image"`

	// Name Container name as reported by the backend.
	Name string `json:"name"`

	// Resources Live resource usage for a container.
	Resources ContainerResources `json:"resources"`

	// RestartCount Number of times the container has been restarted.
	RestartCount int `json:"restartCount"`

	// Status Current state of a container.
	Status ContainerStatus `json:"status"`
}

// ContainerDetail defines model for ContainerDetail.
type ContainerDetail struct {
	// Cmd Default command arguments passed to the entrypoint.
	Cmd []string `json:"cmd"`

	// Device Identifier of the backend device running this container.
	Device string `json:"device"`

	// Entrypoint Container entrypoint command.
	Entrypoint []string `json:"entrypoint"`

	// EnvVariables Environment variables set in the container.
	EnvVariables []EnvVariable `json:"envVariables"`

	// ExitCode Exit code of the last process. Only meaningful when status is not 'running'.
	ExitCode int `json:"exitCode"`

	// FinishedAt Time the container last stopped. Omitted if the container is still running.
	FinishedAt *time.Time `json:"finishedAt,omitempty"`

	// Id Globally unique container identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// Image Container image reference including tag or digest.
	Image string `json:"image"`

	// Labels Container labels as key-value pairs.
	Labels *map[string]string `json:"labels,omitempty"`

	// MemoryLimit Configured memory limit in bytes. 0 means unlimited.
	MemoryLimit Bytes `json:"memoryLimit"`

	// Name Container name as reported by the backend.
	Name string `json:"name"`

	// Networks Networks this container is attached to.
	Networks []ContainerNetwork `json:"networks"`

	// OomKilled Whether the container was killed due to an out-of-memory condition.
	OomKilled bool `json:"oomKilled"`

	// PortBindings Published port mappings between host and container.
	PortBindings []PortBinding `json:"portBindings"`

	// Privileged Whether the container runs in privileged mode.
	Privileged bool `json:"privileged"`

	// Resources Live resource usage for a container.
	Resources ContainerResources `json:"resources"`

	// RestartCount Number of times the container has been restarted.
	RestartCount int `json:"restartCount"`

	// RestartPolicy Container restart policy.
	RestartPolicy ContainerDetailRestartPolicy `json:"restartPolicy"`

	// StartedAt Time the container last started.
	StartedAt time.Time `json:"startedAt"`

	// Status Current state of a container.
	Status ContainerStatus `json:"status"`

	// VolumeBindings Bind mounts and volume mappings.
	VolumeBindings []VolumeMount `json:"volumeBindings"`
}

// ContainerDetailRestartPolicy Container restart policy.
type ContainerDetailRestartPolicy string

// ContainerList List of containers.
type ContainerList struct {
	// Items Containers matching the query. Empty array, never null.
	Items []Container `json:"items"`
}

// ContainerNetwork Network a container is attached to.
type ContainerNetwork struct {
	// Driver Network driver.
	Driver string `json:"driver"`

	// Name Network name.
	Name string `json:"name"`
}

// ContainerResources Live resource usage for a container.
type ContainerResources struct {
	// CpuPercent CPU usage as a percentage of total host CPU.
	CpuPercent float64 `json:"cpuPercent"`

	// MemoryBytes Current memory usage in bytes.
	MemoryBytes Bytes `json:"memoryBytes"`

	// MemoryPercent Memory usage as a percentage of total host memory.
	MemoryPercent float64 `json:"memoryPercent"`
}

// ContainerStatus Current state of a container.
type ContainerStatus string

// EnvVariable An environment variable set in a container.
type EnvVariable struct {
	// Key Environment variable name.
	Key string `json:"key"`

	// Value Environment variable value.
	Value string `json:"value"`
}

// PortBinding Port mapping between a container and the host.
type PortBinding struct {
	// ContainerPort Port exposed by the container.
	ContainerPort int `json:"containerPort"`

	// HostPort Port bound on the host.
	HostPort int `json:"hostPort"`

	// Protocol Transport protocol.
	Protocol PortBindingProtocol `json:"protocol"`
}

// PortBindingProtocol Transport protocol.
type PortBindingProtocol string

// Problem RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code echoed for convenience.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem.
	Title string `json:"title"`

	// Type URI reference identifying the problem type.
	Type string `json:"type"`
}

// VolumeMount Bind mount or volume mapping for a container.
type VolumeMount struct {
	// Destination Mount path inside the container.
	Destination string `json:"destination"`

	// Mode Mount access mode — read-only or read-write.
	Mode VolumeMountMode `json:"mode"`

	// Source Host path or volume name.
	Source string `json:"source"`
}

// VolumeMountMode Mount access mode — read-only or read-write.
type VolumeMountMode string

// DeviceFilter defines model for DeviceFilter.
type DeviceFilter = string

// BadRequest RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type BadRequest = Problem

// Forbidden RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Forbidden = Problem

// InternalServerError RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type InternalServerError = Problem

// NotFound RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type NotFound = Problem

// TooManyRequests RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListContainersParams defines parameters for ListContainers.
type ListContainersParams struct {
	// Device Filter results to a specific backend device by its identifier.
	// Omit to return results from all devices.
	Device *DeviceFilter `form:"device,omitempty" json:"device,omitempty"`
}

// RestartContainerParams defines parameters for RestartContainer.
type RestartContainerParams struct {
	// IdempotencyKey Client-generated key to ensure the request is processed at most once.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// StartContainerParams defines parameters for StartContainer.
type StartContainerParams struct {
	// IdempotencyKey Client-generated key to ensure the request is processed at most once.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// StopContainerParams defines parameters for StopContainer.
type StopContainerParams struct {
	// IdempotencyKey Client-generated key to ensure the request is processed at most once.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List containers
	// (GET /docker/containers)
	ListContainers(w http.ResponseWriter, r *http.Request, params ListContainersParams)
	// Get a container
	// (GET /docker/containers/{containerId})
	GetContainer(w http.ResponseWriter, r *http.Request, containerId string)
	// Restart a container
	// (POST /docker/containers/{containerId}:restart)
	RestartContainer(w http.ResponseWriter, r *http.Request, containerId string, params RestartContainerParams)
	// Start a container
	// (POST /docker/containers/{containerId}:start)
	StartContainer(w http.ResponseWriter, r *http.Request, containerId string, params StartContainerParams)
	// Stop a container
	// (POST /docker/containers/{containerId}:stop)
	StopContainer(w http.ResponseWriter, r *http.Request, containerId string, params StopContainerParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List containers
// (GET /docker/containers)
func (_ Unimplemented) ListContainers(w http.ResponseWriter, r *http.Request, params ListContainersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a container
// (GET /docker/containers/{containerId})
func (_ Unimplemented) GetContainer(w http.ResponseWriter, r *http.Request, containerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restart a container
// (POST /docker/containers/{containerId}:restart)
func (_ Unimplemented) RestartContainer(w http.ResponseWriter, r *http.Request, containerId string, params RestartContainerParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a container
// (POST /docker/containers/{containerId}:start)
func (_ Unimplemented) StartContainer(w http.ResponseWriter, r *http.Request, containerId string, params StartContainerParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop a container
// (POST /docker/containers/{containerId}:stop)
func (_ Unimplemented) StopContainer(w http.ResponseWriter, r *http.Request, containerId string, params StopContainerParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListContainers operation middleware
func (siw *ServerInterfaceWrapper) ListContainers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read:docker"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContainersParams

	// ------------- Optional query parameter "device" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "device", r.URL.Query(), &params.Device, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "device"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContainers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetContainer operation middleware
func (siw *ServerInterfaceWrapper) GetContainer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "containerId" -------------
	var containerId string

	err = runtime.BindStyledParameterWithOptions("simple", "containerId", chi.URLParam(r, "containerId"), &containerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "containerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"read:docker"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContainer(w, r, containerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartContainer operation middleware
func (siw *ServerInterfaceWrapper) RestartContainer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "containerId" -------------
	var containerId string

	err = runtime.BindStyledParameterWithOptions("simple", "containerId", chi.URLParam(r, "containerId"), &containerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "containerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write:docker"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RestartContainerParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartContainer(w, r, containerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartContainer operation middleware
func (siw *ServerInterfaceWrapper) StartContainer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "containerId" -------------
	var containerId string

	err = runtime.BindStyledParameterWithOptions("simple", "containerId", chi.URLParam(r, "containerId"), &containerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "containerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write:docker"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StartContainerParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartContainer(w, r, containerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopContainer operation middleware
func (siw *ServerInterfaceWrapper) StopContainer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "containerId" -------------
	var containerId string

	err = runtime.BindStyledParameterWithOptions("simple", "containerId", chi.URLParam(r, "containerId"), &containerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "containerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"write:docker"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StopContainerParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopContainer(w, r, containerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/docker/containers", wrapper.ListContainers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/docker/containers/{containerId}", wrapper.GetContainer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/docker/containers/{containerId}:restart", wrapper.RestartContainer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/docker/containers/{containerId}:start", wrapper.StartContainer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/docker/containers/{containerId}:stop", wrapper.StopContainer)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ListContainersRequestObject struct {
	Params ListContainersParams
}

type ListContainersResponseObject interface {
	VisitListContainersResponse(w http.ResponseWriter) error
}

type ListContainers200JSONResponse ContainerList

func (response ListContainers200JSONResponse) VisitListContainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListContainers401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListContainers401ApplicationProblemPlusJSONResponse) VisitListContainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListContainers403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListContainers403ApplicationProblemPlusJSONResponse) VisitListContainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListContainers429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListContainers429ApplicationProblemPlusJSONResponse) VisitListContainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListContainers500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ListContainers500ApplicationProblemPlusJSONResponse) VisitListContainersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainerRequestObject struct {
	ContainerId string `json:"containerId"`
}

type GetContainerResponseObject interface {
	VisitGetContainerResponse(w http.ResponseWriter) error
}

type GetContainer200JSONResponse ContainerDetail

func (response GetContainer200JSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainer400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetContainer400ApplicationProblemPlusJSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainer401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetContainer401ApplicationProblemPlusJSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainer403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetContainer403ApplicationProblemPlusJSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainer404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetContainer404ApplicationProblemPlusJSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainer429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetContainer429ApplicationProblemPlusJSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetContainer500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response GetContainer500ApplicationProblemPlusJSONResponse) VisitGetContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RestartContainerRequestObject struct {
	ContainerId string `json:"containerId"`
	Params      RestartContainerParams
}

type RestartContainerResponseObject interface {
	VisitRestartContainerResponse(w http.ResponseWriter) error
}

type RestartContainer204Response struct {
}

func (response RestartContainer204Response) VisitRestartContainerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RestartContainer400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response RestartContainer400ApplicationProblemPlusJSONResponse) VisitRestartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RestartContainer401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RestartContainer401ApplicationProblemPlusJSONResponse) VisitRestartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RestartContainer403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RestartContainer403ApplicationProblemPlusJSONResponse) VisitRestartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RestartContainer404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response RestartContainer404ApplicationProblemPlusJSONResponse) VisitRestartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RestartContainer429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response RestartContainer429ApplicationProblemPlusJSONResponse) VisitRestartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RestartContainer500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response RestartContainer500ApplicationProblemPlusJSONResponse) VisitRestartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartContainerRequestObject struct {
	ContainerId string `json:"containerId"`
	Params      StartContainerParams
}

type StartContainerResponseObject interface {
	VisitStartContainerResponse(w http.ResponseWriter) error
}

type StartContainer204Response struct {
}

func (response StartContainer204Response) VisitStartContainerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type StartContainer400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response StartContainer400ApplicationProblemPlusJSONResponse) VisitStartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartContainer401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response StartContainer401ApplicationProblemPlusJSONResponse) VisitStartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartContainer403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response StartContainer403ApplicationProblemPlusJSONResponse) VisitStartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StartContainer404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response StartContainer404ApplicationProblemPlusJSONResponse) VisitStartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StartContainer429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response StartContainer429ApplicationProblemPlusJSONResponse) VisitStartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type StartContainer500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response StartContainer500ApplicationProblemPlusJSONResponse) VisitStartContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopContainerRequestObject struct {
	ContainerId string `json:"containerId"`
	Params      StopContainerParams
}

type StopContainerResponseObject interface {
	VisitStopContainerResponse(w http.ResponseWriter) error
}

type StopContainer204Response struct {
}

func (response StopContainer204Response) VisitStopContainerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type StopContainer400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response StopContainer400ApplicationProblemPlusJSONResponse) VisitStopContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StopContainer401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response StopContainer401ApplicationProblemPlusJSONResponse) VisitStopContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopContainer403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response StopContainer403ApplicationProblemPlusJSONResponse) VisitStopContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StopContainer404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response StopContainer404ApplicationProblemPlusJSONResponse) VisitStopContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopContainer429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response StopContainer429ApplicationProblemPlusJSONResponse) VisitStopContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type StopContainer500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response StopContainer500ApplicationProblemPlusJSONResponse) VisitStopContainerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List containers
	// (GET /docker/containers)
	ListContainers(ctx context.Context, request ListContainersRequestObject) (ListContainersResponseObject, error)
	// Get a container
	// (GET /docker/containers/{containerId})
	GetContainer(ctx context.Context, request GetContainerRequestObject) (GetContainerResponseObject, error)
	// Restart a container
	// (POST /docker/containers/{containerId}:restart)
	RestartContainer(ctx context.Context, request RestartContainerRequestObject) (RestartContainerResponseObject, error)
	// Start a container
	// (POST /docker/containers/{containerId}:start)
	StartContainer(ctx context.Context, request StartContainerRequestObject) (StartContainerResponseObject, error)
	// Stop a container
	// (POST /docker/containers/{containerId}:stop)
	StopContainer(ctx context.Context, request StopContainerRequestObject) (StopContainerResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListContainers operation middleware
func (sh *strictHandler) ListContainers(w http.ResponseWriter, r *http.Request, params ListContainersParams) {
	var request ListContainersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListContainers(ctx, request.(ListContainersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListContainers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListContainersResponseObject); ok {
		if err := validResponse.VisitListContainersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetContainer operation middleware
func (sh *strictHandler) GetContainer(w http.ResponseWriter, r *http.Request, containerId string) {
	var request GetContainerRequestObject

	request.ContainerId = containerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetContainer(ctx, request.(GetContainerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetContainer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetContainerResponseObject); ok {
		if err := validResponse.VisitGetContainerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestartContainer operation middleware
func (sh *strictHandler) RestartContainer(w http.ResponseWriter, r *http.Request, containerId string, params RestartContainerParams) {
	var request RestartContainerRequestObject

	request.ContainerId = containerId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestartContainer(ctx, request.(RestartContainerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestartContainer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestartContainerResponseObject); ok {
		if err := validResponse.VisitRestartContainerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartContainer operation middleware
func (sh *strictHandler) StartContainer(w http.ResponseWriter, r *http.Request, containerId string, params StartContainerParams) {
	var request StartContainerRequestObject

	request.ContainerId = containerId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartContainer(ctx, request.(StartContainerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartContainer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartContainerResponseObject); ok {
		if err := validResponse.VisitStartContainerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopContainer operation middleware
func (sh *strictHandler) StopContainer(w http.ResponseWriter, r *http.Request, containerId string, params StopContainerParams) {
	var request StopContainerRequestObject

	request.ContainerId = containerId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopContainer(ctx, request.(StopContainerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopContainer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopContainerResponseObject); ok {
		if err := validResponse.VisitStopContainerResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
